//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopCR.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Direccion()
        {
            this.Incidente = new HashSet<Incidente>();
        }
    
        public int DireccionID { get; set; }
        public int UsuarioID { get; set; }
        public string Alias { get; set; }
        public string TextoLibre { get; set; }
        public decimal Latitud { get; set; }
        public decimal Longitud { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocation { get; set; }
        public bool IsDomicilioPrincipal { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incidente> Incidente { get; set; }
    }
}
