//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopCR.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Incidente()
        {
            this.IncidenteAdjunto = new HashSet<IncidenteAdjunto>();
            this.Notificacion = new HashSet<Notificacion>();
        }
    
        public int IncidenteID { get; set; }
        public int UsuarioID { get; set; }
        public Nullable<int> DireccionID { get; set; }
        public decimal Latitud { get; set; }
        public decimal Longitud { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocation { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaReporte { get; set; }
        public byte Estado { get; set; }
        public byte CategoriaIncidenteID { get; set; }
        public Nullable<int> AdministradorID { get; set; }
        public Nullable<System.DateTime> FechaResolucion { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual CategoriaIncidente CategoriaIncidente { get; set; }
        public virtual Direccion Direccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidenteAdjunto> IncidenteAdjunto { get; set; }
        public virtual UsuarioFinal UsuarioFinal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificacion> Notificacion { get; set; }
    }
}
