//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopCR.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion
    {
        public int NotificacionID { get; set; }
        public int UsuarioID { get; set; }
        public int IncidenteID { get; set; }
        public string Mensaje { get; set; }
        public bool IsLeido { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Incidente Incidente { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
