//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopCR.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioFinal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuarioFinal()
        {
            this.Incidente = new HashSet<Incidente>();
        }
    
        public int UsuarioID { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string TelefonoContacto { get; set; }
        public int PuntosConfianza { get; set; }
        public bool AceptaNotificacionesPush { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incidente> Incidente { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
